version: "3"
volumes:
  bundle:
  cache:
services:
  db:
    image: postgres:9.6
    volumes:
      - ./.data/postgres:/var/lib/postgresql/new-data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
  app:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    command: ./start
    image: app:dev
    volumes:
      - .:/app
      - ~/.ssh/temporal:/root/.ssh
      - bundle:/box
    depends_on:
      - db
      - cache
    ports:
      - "3100:3000"
    environment:
      - SECRET_KEY_BASE=this-is-a-secure-secret-key-12-factors
      - POSTGRES_PASSWORD=password
      - POSTGRES_USERNAME=postgres
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - REDIS_PASSWORD=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      - RUN_SEED=false
  bundle:
    image: busybox
    volumes:
      - bundle:/box
