#!/bin/zsh

echo "Removing tmp files"
rm -rf /app/tmp/letter_opener

echo "Starting the application"
/root/.rbenv/bin/rbenv rehash
bundle check || bundle install
bundle exec rake db:create
bundle exec rake db:migrate
#RAILS_ENV=test bundle exec rake db:migrate
if [ RUN_SEED = "true" ]; then
  echo "Running seed"
  bundle exec rake db:seed
fi
bundle exec rails s -b 0.0.0.0

